# Generated by Django 2.0.4 on 2018-04-28 12:31

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(default='spaceholder'),
            preserve_default=False,
        ),
    ]
