# Generated by Django 2.0.4 on 2018-05-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('journal', 'journal'), ('blog', 'blog')], default='journal', max_length=7),
        ),
    ]
