# Generated by Django 2.0.4 on 2018-05-17 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_type'),
    ]

    operations = [

    ]
